
CREATE Table CADASTRO (
    ID_USUARIO INT NOT NULL AUTO_INCREMENT,
    NOME_USUARIO VARCHAR (50) NOT NULL,
    DATA_NASCIMENTO DATETIME NOT NULL,
    NOME_MATERNO VARCHAR (50) NOT NULL,
    CPF INT (11) NOT NULL,
    TELEFONE_CELULAR INT (11) NOT NULL,
    TELEFONE_FIXO INT (11),
    LOGRADOURO VARCHAR (50) NOT NULL,
    NUMERO_RESIDENCIA INT (10) NOT NULL,
    COMPLEMENTO VARCHAR (50) NOT NULL,
    CEP INT (8) NOT NULL,
    LOGIN_CADASTRADO VARCHAR (16) NOT NULL,
    SENHA_CADASTRADA INT (8) NOT NULL,
    PRIMARY KEY (ID_USUARIO)
);